
#include<stdio.h>
#include<conio.h>
#include<dos.h>
main()
{
     int j=0,a=391,b=440,c=493,d=523,e=587,f=659,g=698,h=783,i;
     clrscr();
     sound(a);
     delay(250);
     sound(j);
     delay(20);
     sound(a);
     delay(250);
     sound(b);
     delay(250);
     sound(a);
     delay(250);
     sound(d);
     delay(250);
     sound(c);
     delay(500);
     sound(j);
     delay(300);
     sound(a);
     delay(250);
     sound(a);
     delay(20);
     sound(a);
     delay(250);
     sound(b);
     delay(250);
     sound(a);
     delay(250);
     sound(e);
     delay(250);
     sound(d);
     delay(500);
     sound(a);
     delay(250);
     sound(a);
     delay(250);
     sound(h);
     delay(250);
     sound(f);
     delay(250);
     sound(d);
     delay(250);
     sound(c);
     delay(250);
     sound(b);
     delay(250);
     nosound();
     sound(g);
     delay(250);
     sound(g);
     delay(250);
     sound(f);
     delay(250);
     sound(d);
     delay(250);
     sound(e);
     delay(250);
     sound(d);
     delay(600);

     sound(a);
     delay(250);

     sound(j);
     delay(20);
     sound(a);
     delay(250);
     sound(b);
     delay(250);
     sound(a);
     delay(250);
     sound(d);
     delay(250);
     sound(c);
     delay(500);
     sound(j);
     delay(200);
     nosound();
     getch();
}